// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace orangebackend6.Models
{
    public partial class Apiurlactive
    {
        public string Apiprefix { get; set; }
        public int? Estado { get; set; }
        public DateTime? Fecrea { get; set; }
        public int Id { get; set; }
    }
}