// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace orangebackend6.Models
{
    public partial class Comentario
    {
        public int Idcomentario { get; set; }
        public string Codmsj { get; set; }
        public string Coduser { get; set; }
        public DateTime? Feccrea { get; set; }
        public string Comentario1 { get; set; }
        public int? Estado { get; set; }
    }
}