// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace orangebackend6.Models
{
    public partial class DetalleModulo
    {
        public int? Idmodules { get; set; }
        public string ListaDetalle { get; set; }
        public int Id { get; set; }
    }
}