// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace orangebackend6.Models
{
    public partial class GestionComunidadResult
    {
        public string codcomunity { get; set; }
        public string usuarioCreadorCom { get; set; }
        public int id { get; set; }
        public string nombrecomunity { get; set; }
        public string coduserinvite { get; set; }
        public string color { get; set; }
        public int? estado { get; set; }
        public int? permison { get; set; }
        public string icon { get; set; }
        public string usuarioInvitado { get; set; }
        public string emailInvited { get; set; }
        public DateTime? feccreaCommunity { get; set; }
    }
}
