// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace orangebackend6.Models
{
    public partial class InvitacionesComunidadesResult
    {
        public string nombreinvita { get; set; }
        public string coduserinvita { get; set; }
        public string nombreinvitado { get; set; }
        public string codigoinvitado { get; set; }
        public string descrip { get; set; }
        public int? estado { get; set; }
        public DateTime? feccrea { get; set; }
        public string nombrecomunity { get; set; }
        public int? permison { get; set; }
        public int id { get; set; }
        public string codcomunity { get; set; }
    }
}
