// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace orangebackend6.Models
{
    public partial class ObtenerEmoticonesResult
    {
        public string nombreUsuario { get; set; }
        public int? codemoticon { get; set; }
        public string codpost { get; set; }
        public string coduser { get; set; }
    }
}
