// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace orangebackend6.Models
{
    public partial class Reactioncoment
    {
        public int Id { get; set; }
        public string Coduser { get; set; }
        public int? Idcomentario { get; set; }
        public DateTime? Fecrea { get; set; }
    }
}