// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace orangebackend6.Models
{
    public partial class Taskcomplete
    {
        public int Id { get; set; }
        public string Codmsj { get; set; }
        public DateTime? Feccomplete { get; set; }
        public string Codusercrea { get; set; }
    }
}