// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace orangebackend6.Models
{
    public partial class Community
    {
        public string Codcomunity { get; set; }
        public string Nombrecomunity { get; set; }
        public string Descrip { get; set; }
        public DateTime? Feccrea { get; set; }
        public string Coduserinvite { get; set; }
        public int? Estado { get; set; }
        public int? Permison { get; set; }
        public string Codusercrea { get; set; }
        public string Icon { get; set; }
        public string Color { get; set; }
        public int Id { get; set; }
    }
}