// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace orangebackend6.Models
{
    public partial class Filesupload
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public string Nombrearchivo { get; set; }
        public string Codusercrea { get; set; }
        public DateTime? Feccrea { get; set; }
    }
}