// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using orangebackend6.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace orangebackend6.Models
{
    public partial interface IorangeContextProcedures
    {
        Task<int> CambiarEstadoCommentsAsync(int? codcomments, int? estado, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> CompleteTaskAsync(string cmsj, string ctipo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> EstadoInvitacionAsync(int? estado, string coduser, int? permison, int? type, string codcommunity, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GestionComunidadResult>> GestionComunidadAsync(string codcommunity, int? type, string invitacion, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> GuardarEmoticonAsync(string codpost, int? codemoticon, string coduser, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<InvitacionesComunidadesResult>> InvitacionesComunidadesAsync(int? state, string cuserremit, int? perm, int? type, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> MsjEstadoAsync(int? estado, string cuser, string msj, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerComentariosResult>> ObtenerComentariosAsync(string codmsj, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerCommunityResult>> ObtenerCommunityAsync(string codusercre, int? type, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerEmoticonesResult>> ObtenerEmoticonesAsync(string codpost, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateCommunityAsync(string codcomun, string nomcommun, string icon, string color, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
