// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace orangebackend6.Models
{
    public partial class Listascontrol
    {
        public string Nombrelista { get; set; }
        public decimal? ValorUnitario { get; set; }
        public decimal? Cantidad { get; set; }
        public decimal? PresupuestoInicial { get; set; }
        public int Id { get; set; }
        public string Coduser { get; set; }
        public DateTime? Feccrea { get; set; }
        public string Codcommunity { get; set; }
        public int? Estado { get; set; }
    }
}