// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace orangebackend6.Models
{
    public partial class Mensaje
    {
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Codmsj { get; set; }
        public string Description { get; set; }
        public DateTime? Feccrea { get; set; }
        public string Coduser { get; set; }
        public int? Estado { get; set; }
        public DateTime? Fechacumple { get; set; }
        public string Codtipo { get; set; }
    }
}