// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace orangebackend6.Models
{
    public partial class ObtenerCommunityResult
    {
        public string codcomunity { get; set; }
        public string nombrecomunity { get; set; }
        public string descrip { get; set; }
        public string icon { get; set; }
        public string color { get; set; }
    }
}
